# Generated by Django 5.2.8 on 2025-12-15 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='gebruikers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=25)),
                ('password', models.CharField(max_length=25)),
                ('email', models.CharField(max_length=30)),
                ('role', models.CharField(max_length=25)),
                ('isSuperuser', models.CharField(max_length=20)),
            ],
        ),
    ]
